site_name: GivEnergy Modbus
site_url: https://dewet22.github.io/givenergy-modbus
repo_url: https://github.com/dewet22/givenergy-modbus
repo_name: dewet22/givenergy-modbus
nav:
  - Home: index.md
  - Installation: installation.md
  - Usage: usage.md
  - Modules: api.md
  - Contributing: contributing.md
  - Changelog: changelog.md
theme:
  name: material
  language: en
  palette:
    - media: "(prefers-color-scheme: light)"
      scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-7
        name: Switch to dark mode
    - media: "(prefers-color-scheme: dark)"
      scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/brightness-4
        name: Switch to light mode
  features:
    - navigation.indexes
    - navigation.instant
    - navigation.tabs.sticky
markdown_extensions:
  - pymdownx.emoji:
      emoji_index: !!python/name:material.extensions.emoji.twemoji
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
  - pymdownx.critic
  - pymdownx.caret
  - pymdownx.mark
  - pymdownx.tilde
  - pymdownx.tabbed:
      alternate_style: true
  - attr_list
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.highlight:
      linenums: false
  - pymdownx.superfences
  - pymdownx.inlinehilite
  - pymdownx.details
  - admonition
  - toc:
      baselevel: 2
      permalink: true
  - meta
plugins:
  - include-markdown
  - search:
      lang: en
  - mkdocstrings
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dewet22/givenergy-modbus
      name: Github
    - icon: material/email
      link: "mailto:givenergy-modbus@dewet.org"
