from enum import Enum, auto, unique


class Type(Enum):
    """Type of data register represents."""

    BOOL = auto()
    WORD = auto()  # unsigned single word
    DWORD_HIGH = auto()  # unsigned double word, higher (MSB) address half
    DWORD_LOW = auto()  # unsigned double word, lower (LSB) address half
    SWORD = auto()  # signed single word
    ASCII = auto()
    TIME = auto()


class Scaling(Enum):
    """What scaling factor needs to be applied to a register's value."""

    UNIT = 1
    DECI = 0.1
    CENTI = 0.01


@unique
class Bank(bytes, Enum):
    """Collection of registers by their location in a bank."""

    def __new__(cls, value: int, type_: Type, scaling: Scaling):
        """Allows indexing by register index."""
        obj = bytes.__new__(cls, [value])
        obj._value_ = value
        obj.type = type_  # type: ignore
        obj.scaling = scaling  # type: ignore
        return obj


class HoldingRegisterBank(Bank):
    """Definitions of what registers in the Holding Bank represent."""

    DEVICE_TYPE_CODE = (0, Type.WORD, Scaling.UNIT)
    INV_MODULE_H = (1, Type.DWORD_HIGH, Scaling.UNIT)
    INV_MODULE_L = (2, Type.DWORD_LOW, Scaling.UNIT)
    INPUT_TRACKER_NUM_AND_OUTPUT_PHASE_NUM = (3, Type.WORD, Scaling.UNIT)
    REG004 = (4, Type.WORD, Scaling.UNIT)
    REG005 = (5, Type.WORD, Scaling.UNIT)
    REG006 = (6, Type.WORD, Scaling.UNIT)
    REG007 = (7, Type.WORD, Scaling.UNIT)
    BAT_SERIAL_NUMBER_5 = (8, Type.ASCII, Scaling.UNIT)
    BAT_SERIAL_NUMBER_4 = (9, Type.ASCII, Scaling.UNIT)
    BAT_SERIAL_NUMBER_3 = (10, Type.ASCII, Scaling.UNIT)
    BAT_SERIAL_NUMBER_2 = (11, Type.ASCII, Scaling.UNIT)
    BAT_SERIAL_NUMBER_1 = (12, Type.ASCII, Scaling.UNIT)
    INV_SERIAL_NUMBER_5 = (13, Type.ASCII, Scaling.UNIT)
    INV_SERIAL_NUMBER_4 = (14, Type.ASCII, Scaling.UNIT)
    INV_SERIAL_NUMBER_3 = (15, Type.ASCII, Scaling.UNIT)
    INV_SERIAL_NUMBER_2 = (16, Type.ASCII, Scaling.UNIT)
    INV_SERIAL_NUMBER_1 = (17, Type.ASCII, Scaling.UNIT)
    BATT_FW_VERSION = (18, Type.WORD, Scaling.UNIT)
    DSP_FW_VERSION = (19, Type.WORD, Scaling.UNIT)
    WINTER_MODE = (20, Type.WORD, Scaling.UNIT)  # bool?
    ARM_FW_VERSION = (21, Type.WORD, Scaling.UNIT)
    WIFI_OR_U_DISK = (22, Type.WORD, Scaling.UNIT)
    SELECT_DSP_OR_ARM = (23, Type.WORD, Scaling.UNIT)
    SET_VARIABLE_ADDRESS = (24, Type.WORD, Scaling.UNIT)
    SET_VARIABLE_VALUE = (25, Type.WORD, Scaling.UNIT)
    GRID_PORT_MAX_OUTPUT_POWER = (26, Type.WORD, Scaling.UNIT)
    BAT_POWER_MODE = (27, Type.BOOL, Scaling.UNIT)
    FRE_MODE = (28, Type.WORD, Scaling.UNIT)
    SOC_FORCE_ADJUST = (29, Type.WORD, Scaling.UNIT)
    COMMUNICATE__ADDRESS = (30, Type.WORD, Scaling.UNIT)
    SLOT_2_CHARGE_TIME_START = (31, Type.TIME, Scaling.UNIT)
    SLOT_2_CHARGE_TIME_STOP = (32, Type.TIME, Scaling.UNIT)
    USER_CODE = (33, Type.WORD, Scaling.UNIT)
    MODBUS_VERSION = (34, Type.WORD, Scaling.CENTI)
    SYSTEM_TIME_YEAR = (35, Type.WORD, Scaling.UNIT)
    SYSTEM_TIME_MONTH = (36, Type.WORD, Scaling.UNIT)
    SYSTEM_TIME_DAY = (37, Type.WORD, Scaling.UNIT)
    SYSTEM_TIME_HOUR = (38, Type.WORD, Scaling.UNIT)
    SYSTEM_TIME_MIN = (39, Type.WORD, Scaling.UNIT)
    SYSTEM_TIME_SECOND = (40, Type.WORD, Scaling.UNIT)
    DRM_ENABLE = (41, Type.WORD, Scaling.UNIT)
    CT_ADJUST = (42, Type.WORD, Scaling.UNIT)
    CHG_AND_DISCHARGE_SOC = (43, Type.WORD, Scaling.UNIT)
    DISCHARGE_START_TIME_SLOT2 = (44, Type.TIME, Scaling.UNIT)
    DISCHARGE_END_TIME_SLOT2 = (45, Type.TIME, Scaling.UNIT)
    BMS_VERSION = (46, Type.WORD, Scaling.UNIT)
    B_METER_TYPE = (47, Type.WORD, Scaling.UNIT)
    B_115_METER_DIRECT = (48, Type.WORD, Scaling.UNIT)
    B_418_METER_DIRECT = (49, Type.WORD, Scaling.UNIT)
    ACTIVE_P_RATE = (50, Type.WORD, Scaling.UNIT)
    REACTIVE_P_RATE = (51, Type.WORD, Scaling.UNIT)
    POWER_FACTOR = (52, Type.WORD, Scaling.UNIT)
    INV_STATE = (53, Type.WORD, Scaling.UNIT)
    BAT_TYPE = (54, Type.WORD, Scaling.UNIT)
    BAT_NOMINAL_CAPACITY = (55, Type.WORD, Scaling.UNIT)
    DISCHARGE_START_TIME_SLOT1 = (56, Type.TIME, Scaling.UNIT)
    DISCHARGE_END_TIME_SLOT1 = (57, Type.TIME, Scaling.UNIT)
    AUTO_JUDGE_BAT_TYPE_ENABLE = (58, Type.WORD, Scaling.UNIT)
    DISCHARGE_ENABLE = (59, Type.BOOL, Scaling.UNIT)
    INPUT_START_VOLTAGE = (60, Type.WORD, Scaling.UNIT)
    START_TIME = (61, Type.WORD, Scaling.UNIT)
    RESTART_DELAY_TIME = (62, Type.WORD, Scaling.UNIT)
    V_AC_LOW_OUT = (63, Type.WORD, Scaling.UNIT)
    V_AC_HIGH_OUT = (64, Type.WORD, Scaling.UNIT)
    F_AC_LOW_OUT = (65, Type.WORD, Scaling.UNIT)
    F_AC_HIGH_OUT = (66, Type.WORD, Scaling.UNIT)
    V_AC_LOW_OUT__TIME = (67, Type.WORD, Scaling.UNIT)
    V_AC_HIGH_OUT__TIME = (68, Type.WORD, Scaling.UNIT)
    F_AC_LOW_OUT_TIME = (69, Type.WORD, Scaling.UNIT)
    F_AC_HIGH_OUT_TIME = (70, Type.WORD, Scaling.UNIT)
    V_AC_LOW_IN = (71, Type.WORD, Scaling.UNIT)
    V_AC_HIGH_IN = (72, Type.WORD, Scaling.UNIT)
    F_AC_LOW_IN = (73, Type.WORD, Scaling.UNIT)
    F_AC_HIGH_IN = (74, Type.WORD, Scaling.UNIT)
    V_AC_LOW_IN_TIME = (75, Type.WORD, Scaling.UNIT)
    V_AC_HIGH_IN_TIME = (76, Type.WORD, Scaling.UNIT)
    F_AC_LOW_TIME_IN = (77, Type.WORD, Scaling.UNIT)
    F_AC_HIGH_TIME_IN = (78, Type.WORD, Scaling.UNIT)
    V_AC_LOW_C = (79, Type.WORD, Scaling.UNIT)
    V_AC_HIGH_C = (80, Type.WORD, Scaling.UNIT)
    F_AC_LOW_C = (81, Type.WORD, Scaling.UNIT)
    F_AC_HIGH_C = (82, Type.WORD, Scaling.UNIT)
    U_10_MIN = (83, Type.WORD, Scaling.UNIT)
    ISO1 = (84, Type.WORD, Scaling.UNIT)
    ISO2 = (85, Type.WORD, Scaling.UNIT)
    GFCI_I_1 = (86, Type.WORD, Scaling.UNIT)
    GFCI_TIME_1 = (87, Type.WORD, Scaling.UNIT)
    GFCI_I_2 = (88, Type.WORD, Scaling.UNIT)
    GFCI_TIME_2 = (89, Type.WORD, Scaling.UNIT)
    DCI_I_1 = (90, Type.WORD, Scaling.UNIT)
    DCI_TIME_1 = (91, Type.WORD, Scaling.UNIT)
    DCI_I_2 = (92, Type.WORD, Scaling.UNIT)
    DCI_TIME_2 = (93, Type.WORD, Scaling.UNIT)
    CHARGE_START_TIME_SLOT1 = (94, Type.TIME, Scaling.UNIT)
    CHARGE_END_TIME_SLOT1 = (95, Type.TIME, Scaling.UNIT)
    BAT_SMART_CHARGE = (96, Type.BOOL, Scaling.UNIT)
    DISCHARGE_LOW_LIMIT = (97, Type.WORD, Scaling.UNIT)
    CHARGER_HIGH_LIMIT = (98, Type.WORD, Scaling.UNIT)
    PV1_VOLT_ADJUST = (99, Type.WORD, Scaling.UNIT)
    PV2_VOLT_ADJUST = (100, Type.WORD, Scaling.UNIT)
    GRID_R_VOLT_ADJUST = (101, Type.WORD, Scaling.UNIT)
    GRID_S_VOLT_ADJUST = (102, Type.WORD, Scaling.UNIT)
    GRID_T_VOLT_ADJUST = (103, Type.WORD, Scaling.UNIT)
    GRID_POWER_ADJUST = (104, Type.WORD, Scaling.UNIT)
    BAT_VOLT_ADJUST = (105, Type.WORD, Scaling.UNIT)
    PV1_POWER_ADJUST = (106, Type.WORD, Scaling.UNIT)
    PV2_POWER_ADJUST = (107, Type.WORD, Scaling.UNIT)
    BAT_LOW_FORCE_CHARGE_TIME = (108, Type.WORD, Scaling.UNIT)
    BMS_TYPE = (109, Type.WORD, Scaling.UNIT)
    SHALLOW_CHARGE = (110, Type.WORD, Scaling.UNIT)
    BAT_CHARGE_LIMIT = (111, Type.WORD, Scaling.UNIT)
    BAT_DISCHARGE_LIMIT = (112, Type.WORD, Scaling.UNIT)
    BUZZER_SW = (113, Type.WORD, Scaling.UNIT)
    BAT_POWER_RESERVE = (114, Type.WORD, Scaling.UNIT)
    ISLAND_CHECK_CONTINUE = (115, Type.WORD, Scaling.UNIT)
    TARGET_SOC = (116, Type.WORD, Scaling.UNIT)
    CHG_SOC_STOP2 = (117, Type.WORD, Scaling.UNIT)
    DISCHARGE_SOC_STOP2 = (118, Type.WORD, Scaling.UNIT)
    CHG_SOC_STOP = (119, Type.WORD, Scaling.UNIT)
    DISCHARGE_SOC_STOP = (120, Type.WORD, Scaling.UNIT)


class InputRegisterBank(Bank):
    """Definitions of what registers in the Input Bank represent."""

    INV_STATUS = (0, Type.WORD, Scaling.UNIT)
    V_PV1 = (1, Type.WORD, Scaling.DECI)
    V_PV2 = (2, Type.WORD, Scaling.DECI)
    P_BUS_INSIDE_VOLTAGE = (3, Type.WORD, Scaling.DECI)
    N_BUS_INSIDE_VOLTAGE = (4, Type.WORD, Scaling.DECI)
    SINGLE_PHASE_GRID_VOLTAGE = (5, Type.WORD, Scaling.DECI)
    BAT_THROUGHPUT_H = (6, Type.DWORD_HIGH, Scaling.DECI)
    BAT_THROUGHPUT_L = (7, Type.DWORD_LOW, Scaling.DECI)
    I_PV1_INPUT = (8, Type.WORD, Scaling.CENTI)
    I_PV2_INPUT = (9, Type.WORD, Scaling.CENTI)
    I_GRID_OUTPUT_SINGLE_PHASE = (10, Type.WORD, Scaling.CENTI)
    PV_TOTAL_GENERATING_CAPACITY_H = (11, Type.DWORD_HIGH, Scaling.DECI)
    PV_TOTAL_GENERATING_CAPACITY_L = (12, Type.DWORD_LOW, Scaling.DECI)
    F_GRID_THREE_SINGLE_PHASE = (13, Type.WORD, Scaling.CENTI)
    CHARGE_STATUS = (14, Type.WORD, Scaling.UNIT)
    V_HIGHBRIGH_BUS = (15, Type.WORD, Scaling.UNIT)  # high voltage bus?
    PF_INV_OUTPUT_NOW = (16, Type.WORD, Scaling.UNIT)
    E_PV1_DAY = (17, Type.WORD, Scaling.DECI)
    P_PV1_INPUT = (18, Type.WORD, Scaling.UNIT)
    E_PV2_DAY = (19, Type.WORD, Scaling.DECI)
    P_PV2_INPUT = (20, Type.WORD, Scaling.UNIT)
    E_GRID_OUT_TOTAL_H = (21, Type.DWORD_HIGH, Scaling.DECI)
    E_GRID_OUT_TOTAL_L = (22, Type.DWORD_LOW, Scaling.DECI)
    PV_MATE = (23, Type.WORD, Scaling.DECI)
    P_GRID_THREE_SINGLE_PHASE_OUTPUT_L = (24, Type.SWORD, Scaling.UNIT)
    E_GRID_OUT_DAY = (25, Type.WORD, Scaling.DECI)
    E_GRID_IN_DAY = (26, Type.WORD, Scaling.DECI)
    E_INV_IN_TOTAL_H = (27, Type.DWORD_HIGH, Scaling.DECI)
    E_INV_IN_TOTAL_L = (28, Type.DWORD_LOW, Scaling.DECI)
    E_DISCHARGE_YEAR_L = (29, Type.WORD, Scaling.DECI)
    P_GRID_OUTPUT = (30, Type.SWORD, Scaling.UNIT)
    P_BACKUP = (31, Type.WORD, Scaling.UNIT)
    P_GRID_IN_TOTAL_H = (32, Type.DWORD_HIGH, Scaling.DECI)
    P_GRID_IN_TOTAL_L = (33, Type.DWORD_LOW, Scaling.DECI)
    REG034 = (34, Type.WORD, Scaling.UNIT)
    E_TOTAL_LOAD_DAY = (35, Type.WORD, Scaling.DECI)
    E_BAT_CHARGE_DAY = (36, Type.WORD, Scaling.DECI)
    E_BAT_DISCHARGE_DAY = (37, Type.WORD, Scaling.DECI)
    P_COUNTDOWN = (38, Type.WORD, Scaling.UNIT)
    FAULT_CODE_H = (39, Type.DWORD_HIGH, Scaling.UNIT)
    FAULT_CODE_L = (40, Type.DWORD_LOW, Scaling.UNIT)
    TEMP_INV = (41, Type.WORD, Scaling.DECI)
    P_LOAD_TOTAL = (42, Type.WORD, Scaling.UNIT)
    P_GRID_APPARENT = (43, Type.WORD, Scaling.UNIT)
    E_GENERATED_DAY = (44, Type.WORD, Scaling.DECI)
    E_GENERATED_H = (45, Type.DWORD_HIGH, Scaling.DECI)
    E_GENERATED_L = (46, Type.DWORD_LOW, Scaling.DECI)
    WORK_TIME_TOTAL_H = (47, Type.DWORD_HIGH, Scaling.UNIT)
    WORK_TIME_TOTAL_L = (48, Type.DWORD_LOW, Scaling.UNIT)
    SYSTEM_MODE = (49, Type.WORD, Scaling.UNIT)
    V_BAT = (50, Type.WORD, Scaling.CENTI)
    I_BAT = (51, Type.SWORD, Scaling.CENTI)
    P_BAT = (52, Type.SWORD, Scaling.UNIT)
    V_OUTPUT = (53, Type.WORD, Scaling.DECI)
    F_OUTPUT = (54, Type.WORD, Scaling.CENTI)
    TEMP_CHARGER = (55, Type.WORD, Scaling.DECI)
    TEMP_BAT = (56, Type.WORD, Scaling.DECI)
    CHARGER_WARNING_CODE = (57, Type.WORD, Scaling.UNIT)
    P_GRID_PORT = (58, Type.WORD, Scaling.CENTI)
    BAT_PERCENT = (59, Type.WORD, Scaling.UNIT)
    REG060 = (60, Type.WORD, Scaling.UNIT)  # actually invalid?
    E_BAT_DISCHARGE_AC_TOTAL = (105, Type.WORD, Scaling.DECI)
    E_BAT_CHARGE_AC_TOTAL = (106, Type.WORD, Scaling.DECI)
    E_BAT_DISCHARGE_TOTAL = (180, Type.WORD, Scaling.DECI)
    E_BAT_CHARGE_TOTAL = (181, Type.WORD, Scaling.DECI)
