import datetime
import warnings

import pytest

from givenergy_modbus.model import TimeSlot
from givenergy_modbus.model.inverter import (
    BatteryCalibrationStage,
    BatteryPowerMode,
    BatteryType,
    MeterType,
    Model,
    PowerFactorFunctionModel,
    SinglePhaseInverter,
    Status,
    UsbDevice,
    resolve_model,
)
from givenergy_modbus.model.register_cache import RegisterCache


def test_inverter():
    i1 = SinglePhaseInverter()
    i2 = SinglePhaseInverter.from_register_cache(RegisterCache())

    assert (
        i1.model_dump()
        == i2.model_dump()
        == {
            "active_power_rate": None,
            "arm_firmware_version": None,
            "battery_max_power": None,
            "battery_calibration_stage": None,
            "battery_capacity_ah": None,

            "battery_capacity_kwh": None,
            "battery_power_mode": None,
            "battery_type": None,
            "bms_firmware_version": None,
            "charge_slot_2": None,
            "charge_soc": None,
            "device_type_code": None,
            "discharge_slot_1": None,
            "discharge_slot_2": None,
            "discharge_soc": None,
            "dsp_firmware_version": None,
            "enable_60hz_freq_mode": None,
            "enable_ammeter": None,
            "enable_auto_judge_battery_type": None,
            "enable_charge_target": None,
            "enable_discharge": None,
            "enable_drm_rj45_port": None,
            "enable_inverter": None,
            "enable_inverter_auto_restart": None,
            "enable_reversed_115_meter": None,
            "enable_reversed_418_meter": None,
            "firmware_version": None,
            "first_battery_bms_firmware_version": None,
            "first_battery_serial_number": None,
            "grid_port_max_power_output": None,
            "meter_type": None,
            "modbus_address": None,
            "modbus_version": None,
            "model": None,
            "inverter_max_power": None,
            "module": None,
            "num_mppt": None,
            "num_phases": None,
            "power_factor": None,
            "reactive_power_rate": None,
            "enable_reversed_ct_clamp": None,
            "select_arm_chip": None,
            "serial_number": None,
            "status": None,
            "v_pv1": None,
            "v_pv2": None,
            "v_p_bus": None,
            "v_n_bus": None,
            "v_ac1": None,
            "e_battery_throughput": None,
            "i_pv1": None,
            "i_pv2": None,
            "i_ac1": None,
            "e_pv_total": None,
            "f_ac1": None,
            "charge_status": None,
            "v_highbrigh_bus": None,
            "pf_inverter_output_now": None,
            "e_pv1_day": None,
            "p_pv1": None,
            "e_pv2_day": None,
            "p_pv2": None,
            "e_grid_out_total": None,
            "e_solar_diverter": None,
            "p_grid_out_ph1": None,
            "e_grid_out_day": None,
            "e_grid_in_day": None,
            "e_inverter_in_total": None,
            "e_discharge_year": None,
            "p_grid_out": None,
            "p_backup": None,
            "e_grid_in_total": None,
            "e_load_day": None,
            "e_battery_charge_day": None,
            "e_battery_discharge_day": None,
            "countdown": None,
            "fault_code": None,
            "t_inverter_heatsink": None,
            "p_load_demand": None,
            "p_grid_apparent": None,
            "e_inverter_out_day": None,
            "e_inverter_out_total": None,
            "work_time_total": None,
            "system_mode": None,
            "v_battery": None,
            "i_battery": None,
            "p_battery": None,
            "v_ac1_output": None,
            "f_ac1_output": None,
            "t_charger": None,
            "t_battery": None,
            "charger_warning_code": None,
            "i_grid_port": None,
            "battery_soc": None,
            "system_time": None,
            "usb_device_inserted": None,
            "user_code": None,
            "variable_address": None,
            "variable_value": None,
            "v_pv_start": None,
            "restart_delay_time": None,
            "start_countdown_timer": None,
            "enable_charge": None,
            "charge_slot_1": None,
            "battery_high_voltage_protection_limit": None,
            "battery_low_voltage_protection_limit": None,
            # 'island_check_continue': None,
            "enable_buzzer": None,
            "enable_bms_read": None,
            "discharge_soc_stop_2": None,
            "charge_target_soc": None,
            "charge_soc_stop_2": None,
            "charge_soc_stop_1": None,
            "battery_soc_reserve": None,
            "battery_low_force_charge_time": None,
            "battery_discharge_min_power_reserve": None,
            "battery_discharge_limit": None,
            "battery_charge_limit": None,
            "debug_inverter": None,
            "discharge_soc_stop_1": None,
            "enable_above_6kw_system": None,
            "enable_battery_cable_impedance_alarm": None,
            "enable_battery_on_pv_or_grid": None,
            "enable_frequency_derating": None,
            "enable_g100_limit_switch": None,
            "enable_local_command_test": None,
            "enable_low_voltage_fault_ride_through": None,
            "enable_spi": None,
            "enable_ups_mode": None,
            "frequency_load_limit_rate": None,
            "power_factor_function_model": None,
            "start_system_auto_test": None,
            "threephase_abc": None,
            "threephase_balance_1": None,
            "threephase_balance_2": None,
            "threephase_balance_3": None,
            "threephase_balance_mode": None,
            "cmd_bms_flash_update": None,
            "enable_standard_self_consumption_logic": None,
            "e_battery_charge_today": None,
            "e_battery_charge_total2": None,
            "e_battery_discharge_today": None,
            "e_battery_discharge_total2": None,
            "pv_power_setting": None,
            "e_inverter_export_total": None,
            "battery_voltage_adjust": None,
            "inverter_reboot": None,
            "enable_rtc": None,
            "inverter_errors": None,
            "inverter_fault_messages": None,
            "charge_target_soc_1": None,
            "charge_slot_2_x": None,
            "charge_target_soc_2": None,
            "charge_slot_3": None,
            "charge_target_soc_3": None,
            "charge_slot_4": None,
            "charge_target_soc_4": None,
            "charge_slot_5": None,
            "charge_target_soc_5": None,
            "charge_slot_6": None,
            "charge_target_soc_6": None,
            "charge_slot_7": None,
            "charge_target_soc_7": None,
            "charge_slot_8": None,
            "charge_target_soc_8": None,
            "charge_slot_9": None,
            "charge_target_soc_9": None,
            "charge_slot_10": None,
            "charge_target_soc_10": None,
            "discharge_target_soc_1": None,
            "discharge_target_soc_2": None,
            "discharge_slot_3": None,
            "discharge_target_soc_3": None,
            "discharge_slot_4": None,
            "discharge_target_soc_4": None,
            "discharge_slot_5": None,
            "discharge_target_soc_5": None,
            "discharge_slot_6": None,
            "discharge_target_soc_6": None,
            "discharge_slot_7": None,
            "discharge_target_soc_7": None,
            "discharge_slot_8": None,
            "discharge_target_soc_8": None,
            "discharge_slot_9": None,
            "discharge_target_soc_9": None,
            "discharge_slot_10": None,
            "discharge_target_soc_10": None,
            "battery_charge_limit_ac": None,
            "battery_discharge_limit_ac": None,
            "battery_pause_mode": None,
            "battery_pause_slot_1": None,
            "e_battery_discharge_2": None,
            "e_battery_charge_2": None,
            "e_battery_discharge_day_2": None,
            "e_battery_charge_day_2": None,
            "p_combined_generation": None,
        }
    )


def test_from_registers(register_cache):
    """Ensure we can return a dict view of inverter data."""
    i = SinglePhaseInverter.from_register_cache(register_cache)
    assert i.serial_number == "SA1234G567"
    assert i.model == Model.HYBRID
    assert getattr(i, "serial_number") == "SA1234G567"
    with pytest.raises(TypeError, match="'SinglePhaseInverter' object is not subscriptable"):
        i["serial_number"]

    assert i.model_dump() == {
        "battery_charge_limit": 50,
        "battery_discharge_limit": 50,
        "battery_discharge_min_power_reserve": 4,
        "battery_high_voltage_protection_limit": 58.50,
        "battery_low_force_charge_time": 6,
        "battery_low_voltage_protection_limit": 43.20,
        # 'battery_percent': 4,
        "battery_soc_reserve": 4,
        # 'battery_voltage_adjust': 0,
        "charge_slot_1": TimeSlot.from_repr(30, 430),
        "charge_soc_stop_1": 0,
        "charge_soc_stop_2": 0,
        # 'charge_status': 0,
        "charge_target_soc": 100,
        # 'charger_warning_code': 0,
        "cmd_bms_flash_update": None,
        # 'dci_1_i': 0.0,
        # 'dci_1_time': 0,
        # 'dci_2_i': 0.0,
        # 'dci_2_time': 0,
        # 'dci_fault_value': 0.0,
        "debug_inverter": None,
        "discharge_soc_stop_1": None,
        "discharge_soc_stop_2": 0,
        # 'e_battery_charge_day': 9.0,
        # 'e_battery_charge_day_2': 9.0,
        "e_battery_charge_today": None,
        # 'e_battery_charge_total': 174.4,
        "e_battery_charge_total2": None,
        # 'e_battery_discharge_day': 8.9,
        # 'e_battery_discharge_day_2': 8.9,
        "e_battery_discharge_today": None,
        # 'e_battery_discharge_total': 169.6,
        "e_battery_discharge_total2": None,
        # 'e_battery_throughput_total': 183.2,
        # 'e_discharge_year': 0.0,
        # 'e_grid_in_day': 20.9,
        # 'e_grid_in_total': 365.3,
        # 'e_grid_out_day': 0.0,
        # 'e_grid_out_total': 0.6,
        "e_inverter_export_total": None,
        # 'e_inverter_in_day': 9.3,
        # 'e_inverter_in_total': 94.6,
        # 'e_inverter_out_day': 8.1,
        # 'e_inverter_out_total': 93.0,
        # 'e_pv1_day': 0.4,
        # 'e_pv2_day': 0.5,
        # 'e_pv_day': 0.9,
        # 'e_pv_total': 15.9,
        # 'e_solar_diverter': 0.0,
        "enable_above_6kw_system": None,
        "enable_battery_cable_impedance_alarm": None,
        "enable_battery_on_pv_or_grid": None,
        "enable_bms_read": True,
        "enable_buzzer": False,
        "enable_charge": True,
        "enable_frequency_derating": None,
        "enable_g100_limit_switch": None,
        "enable_low_voltage_fault_ride_through": None,
        "enable_spi": None,
        "enable_standard_self_consumption_logic": None,
        "enable_ups_mode": None,
        # 'f_ac1': 49.9,
        # 'f_ac_fault_value': 0.0,
        # 'f_ac_high_c': 52.0,
        # 'f_ac_high_in': 52.0,
        # 'f_ac_high_in_time': 28,
        # 'f_ac_high_out': 51.98,
        # 'f_ac_high_out_time': 28,
        # 'f_ac_low_c': 47.0,
        # 'f_ac_low_in': 47.45,
        # 'f_ac_low_in_time': 1,
        # 'f_ac_low_out': 47.0,
        # 'f_ac_low_out_time': 24,
        # 'f_eps_backup': 49.86,
        # 'fault_code': 0,
        "frequency_load_limit_rate": None,
        # 'gfci_1_i': 0.0,
        # 'gfci_1_time': 0,
        # 'gfci_2_i': 0.0,
        # 'gfci_2_time': 0,
        # 'gfci_fault_value': 0.0,
        # 'grid_power_adjust': 0,
        # 'grid_r_voltage_adjust': 0,
        # 'grid_s_voltage_adjust': 0,
        # 'grid_t_voltage_adjust': 0,
        # 'i_ac1': 0.0,
        # 'i_battery': 0.0,
        # 'i_grid_port': 2.92,
        # 'i_pv1': 0.0,
        # 'i_pv2': 0.0,
        # 'inverter_countdown': 30,
        # 'inverter_reboot': 0,
        # 'inverter_status': 0,
        # 'island_check_continue': 0,
        # 'iso1': 0,
        # 'iso2': 0,
        # 'iso_fault_value': 0.0,
        "enable_local_command_test": None,
        # 'p_battery': 0,
        # 'p_eps_backup': 0,
        # 'p_grid_apparent': 680,
        # 'p_grid_out': -342,
        # 'p_inverter_out': 0,
        # 'p_load_demand': 342,
        # 'p_pv': 13,
        # 'p_pv1': 4,
        # 'p_pv2': 9,
        # 'pf_cmd_memory_state': False,
        # 'pf_inverter_out': -0.521,
        # 'pf_limit_lp1_lp': 0,
        # 'pf_limit_lp1_pf': -1.0,
        # 'pf_limit_lp2_lp': 0,
        # 'pf_limit_lp2_pf': -1.0,
        # 'pf_limit_lp3_lp': 0,
        # 'pf_limit_lp3_pf': -1.0,
        # 'pf_limit_lp4_lp': 0,
        # 'pf_limit_lp4_pf': -1.0,
        "power_factor_function_model": None,
        # 'pv1_power_adjust': 0,
        # 'pv1_voltage_adjust': 0,
        # 'pv2_power_adjust': 0,
        # 'pv2_voltage_adjust': 0,
        "pv_power_setting": None,
        "v_pv_start": 150.0,
        # 'real_v_f_value': 0.0,
        # 'remote_bms_restart': False,
        "restart_delay_time": 30,
        # 'safety_time_limit': 0.0,
        # 'safety_v_f_limit': 0.0,
        "start_countdown_timer": 30,
        "start_system_auto_test": None,
        # 'system_mode': 1,
        # 'temp_battery': 17.0,
        # 'temp_charger': 22.3,
        # 'temp_fault_value': 0.0,
        # 'temp_inverter_heatsink': 22.2,
        # 'test_treat_time': 0,
        # 'test_treat_value': 0.0,
        # 'test_value': 0.0,
        "threephase_abc": None,
        "threephase_balance_1": None,
        "threephase_balance_2": None,
        "threephase_balance_3": None,
        "threephase_balance_mode": None,
        # 'usb_device_inserted': 2,
        # 'v_10_min_protection': 274.0,
        # 'v_ac1': 236.7,
        # 'v_ac_fault_value': 0.0,
        # 'v_ac_high_c': 283.7,
        # 'v_ac_high_in': 262.0,
        # 'v_ac_high_in_time': 52,
        # 'v_ac_high_out': 274.0,
        # 'v_ac_high_out_time': 27,
        # 'v_ac_low_c': 175.5,
        # 'v_ac_low_in': 184.0,
        # 'v_ac_low_in_time': 126,
        # 'v_ac_low_out': 184.0,
        # 'v_ac_low_out_time': 126,
        # 'v_battery': 49.91,
        # 'v_eps_backup': 235.6,
        # 'v_highbrigh_bus': 12,
        # 'v_n_bus': 0.0,
        # 'v_p_bus': 7.0,
        # 'v_pv1': 1.4,
        # 'v_pv2': 1.0,
        # 'v_pv_fault_value': 0.0,
        # 'work_time_total': 213,
        "active_power_rate": 100,
        "arm_firmware_version": 449,
        "battery_max_power": 2600,
        "battery_calibration_stage": BatteryCalibrationStage.OFF,
        "battery_capacity_ah": 160,

        "battery_capacity_kwh": 8.192,
        "battery_power_mode": BatteryPowerMode.SELF_CONSUMPTION,
        "battery_type": BatteryType.LITHIUM,
        "bms_firmware_version": 101,
        "charge_slot_2": TimeSlot(datetime.time(0, 0), datetime.time(0, 4)),
        "charge_soc": 0,
        "device_type_code": "2001",
        "discharge_slot_1": TimeSlot.from_repr(0, 0),
        "discharge_slot_2": TimeSlot.from_repr(0, 0),
        "discharge_soc": 0,
        "dsp_firmware_version": 449,
        "enable_60hz_freq_mode": False,
        "enable_ammeter": True,
        "enable_auto_judge_battery_type": True,
        "enable_charge_target": True,
        "enable_discharge": False,
        "enable_drm_rj45_port": True,
        "enable_inverter": True,
        "enable_inverter_auto_restart": False,
        "enable_reversed_115_meter": False,
        "enable_reversed_418_meter": False,
        "enable_reversed_ct_clamp": True,
        "firmware_version": "D0.449-A0.449",
        "first_battery_bms_firmware_version": 3005,
        "first_battery_serial_number": "BG1234G567",
        "grid_port_max_power_output": 6000,
        "meter_type": MeterType.EM115,
        "modbus_address": 0x11,
        "modbus_version": "1.40",
        "model": Model.HYBRID,
        "inverter_max_power": 5000,
        "module": "00030832",
        "num_mppt": 2,
        "num_phases": 1,
        "power_factor": 0,
        "reactive_power_rate": 0,
        "select_arm_chip": False,
        "serial_number": "SA1234G567",
        "status": Status.WAITING,
        "v_pv1": 1.4,
        "v_pv2": 1.0,
        "v_p_bus": 7.0,
        "v_n_bus": 0.0,
        "v_ac1": 236.7,
        "e_battery_throughput": 183.2,
        "i_pv1": 0.0,
        "i_pv2": 0.0,
        "i_ac1": 0.0,
        "e_pv_total": 15.9,
        "f_ac1": 49.9,
        "charge_status": 0,
        "v_highbrigh_bus": 1.2,
        "pf_inverter_output_now": 4790,
        "e_pv1_day": 0.4,
        "p_pv1": 4,
        "e_pv2_day": 0.5,
        "p_pv2": 9,
        "e_grid_out_total": 0.6,
        "e_solar_diverter": 0.0,
        "p_grid_out_ph1": 0,
        "e_grid_out_day": 0.0,
        "e_grid_in_day": 20.9,
        "e_inverter_in_total": 94.6,
        "e_discharge_year": 0.0,
        "p_grid_out": -342,
        "p_backup": 0,
        "e_grid_in_total": 365.3,
        "e_load_day": 9.3,
        "e_battery_charge_day": 9.0,
        "e_battery_discharge_day": 8.9,
        "countdown": 30,
        "fault_code": "00000000",
        "t_inverter_heatsink": 22.2,
        "p_load_demand": 342,
        "p_grid_apparent": 680,
        "e_inverter_out_day": 8.1,
        "e_inverter_out_total": 93.0,
        "work_time_total": 213,
        "system_mode": 1,
        "v_battery": 49.91,
        "i_battery": 0.0,
        "p_battery": 0,
        "v_ac1_output": 235.6,
        "f_ac1_output": 49.86,
        "t_charger": 22.3,
        "t_battery": 17.0,
        "charger_warning_code": 0,
        "i_grid_port": 2.92,
        "battery_soc": 4,
        "system_time": datetime.datetime(2022, 1, 1, 23, 57, 19),
        "usb_device_inserted": UsbDevice.DISK,
        "user_code": 7,
        "variable_address": 32768,
        "variable_value": 30235,
        "battery_voltage_adjust": 0.0,
        "inverter_reboot": None,
        "enable_rtc": None,
        "inverter_errors": None,
        "inverter_fault_messages": None,
        "charge_target_soc_1": None,
        "charge_slot_2_x": None,
        "charge_target_soc_2": None,
        "charge_slot_3": None,
        "charge_target_soc_3": None,
        "charge_slot_4": None,
        "charge_target_soc_4": None,
        "charge_slot_5": None,
        "charge_target_soc_5": None,
        "charge_slot_6": None,
        "charge_target_soc_6": None,
        "charge_slot_7": None,
        "charge_target_soc_7": None,
        "charge_slot_8": None,
        "charge_target_soc_8": None,
        "charge_slot_9": None,
        "charge_target_soc_9": None,
        "charge_slot_10": None,
        "charge_target_soc_10": None,
        "discharge_target_soc_1": None,
        "discharge_target_soc_2": None,
        "discharge_slot_3": None,
        "discharge_target_soc_3": None,
        "discharge_slot_4": None,
        "discharge_target_soc_4": None,
        "discharge_slot_5": None,
        "discharge_target_soc_5": None,
        "discharge_slot_6": None,
        "discharge_target_soc_6": None,
        "discharge_slot_7": None,
        "discharge_target_soc_7": None,
        "discharge_slot_8": None,
        "discharge_target_soc_8": None,
        "discharge_slot_9": None,
        "discharge_target_soc_9": None,
        "discharge_slot_10": None,
        "discharge_target_soc_10": None,
        "battery_charge_limit_ac": None,
        "battery_discharge_limit_ac": None,
        "battery_pause_mode": None,
        "battery_pause_slot_1": None,
        "e_battery_discharge_2": 169.6,
        "e_battery_charge_2": 174.4,
        "e_battery_discharge_day_2": 8.9,
        "e_battery_charge_day_2": 9.0,
        "p_combined_generation": None,
    }


def test_from_registers_actual_data(register_cache_inverter_daytime_discharging_with_solar_generation):
    """Ensure we can instantiate an SinglePhaseInverter from actual register data."""
    i = SinglePhaseInverter.from_register_cache(register_cache_inverter_daytime_discharging_with_solar_generation)
    assert i.serial_number == "SA1234G567"
    assert i.model == Model.HYBRID
    assert i.model_dump() == {
        "battery_charge_limit": 50,
        "battery_discharge_limit": 50,
        "battery_discharge_min_power_reserve": 4,
        "battery_high_voltage_protection_limit": 58.50,
        "battery_low_force_charge_time": 6,
        "battery_low_voltage_protection_limit": 43.20,
        # 'battery_percent': 68,
        "battery_soc_reserve": 4,
        # 'battery_voltage_adjust': 0,
        "charge_slot_1": TimeSlot.from_repr(30, 430),
        "charge_soc_stop_1": 0,
        "charge_soc_stop_2": 0,
        # 'charge_status': 5,
        "charge_target_soc": 100,
        # 'charger_warning_code': 0,
        "cmd_bms_flash_update": None,
        # 'dci_1_i': 0.0,
        # 'dci_1_time': 0,
        # 'dci_2_i': 0.0,
        # 'dci_2_time': 0,
        # 'dci_fault_value': 0.0,
        "debug_inverter": 0,
        "discharge_soc_stop_1": 0,
        "discharge_soc_stop_2": 0,
        # 'e_battery_charge_day': 9.1,
        # 'e_battery_charge_day_2': 9.1,
        "e_battery_charge_today": None,
        # 'e_battery_charge_total': 183.5,
        "e_battery_charge_total2": None,
        # 'e_battery_discharge_day': 3.4,
        # 'e_battery_discharge_day_2': 3.4,
        "e_battery_discharge_today": None,
        # 'e_battery_discharge_total': 173.0,
        "e_battery_discharge_total2": None,
        # 'e_battery_throughput_total': 356.5,
        # 'e_discharge_year': 0.0,
        # 'e_grid_in_day': 19.8,
        # 'e_grid_in_total': 624.2,
        # 'e_grid_out_day': 0.0,
        # 'e_grid_out_total': 0.9,
        "e_inverter_export_total": None,
        # 'e_inverter_in_day': 9.3,
        # 'e_inverter_in_total': 188.1,
        # 'e_inverter_out_day': 3.8,
        # 'e_inverter_out_total': 172.5,
        # 'e_pv1_day': 0.4,
        # 'e_pv2_day': 0.6,
        # 'e_pv_day': 1.0,
        # 'e_pv_total': 26.3,
        # 'e_solar_diverter': 0.0,
        "enable_above_6kw_system": False,
        "enable_battery_cable_impedance_alarm": False,
        "enable_battery_on_pv_or_grid": False,
        "enable_bms_read": True,
        "enable_buzzer": False,
        "enable_charge": True,
        "enable_frequency_derating": True,
        "enable_g100_limit_switch": False,
        "enable_low_voltage_fault_ride_through": False,
        "enable_spi": True,
        "enable_standard_self_consumption_logic": None,
        "enable_ups_mode": False,
        # 'f_ac1': 49.96,
        # 'f_ac_fault_value': 0.0,
        # 'f_ac_high_c': 52.0,
        # 'f_ac_high_in': 52.0,
        # 'f_ac_high_in_time': 28,
        # 'f_ac_high_out': 51.98,
        # 'f_ac_high_out_time': 28,
        # 'f_ac_low_c': 47.0,
        # 'f_ac_low_in': 47.45,
        # 'f_ac_low_in_time': 1,
        # 'f_ac_low_out': 47.0,
        # 'f_ac_low_out_time': 24,
        # 'f_eps_backup': 49.92,
        # 'fault_code': 0,
        "frequency_load_limit_rate": 24,
        # 'gfci_1_i': 0.0,
        # 'gfci_1_time': 0,
        # 'gfci_2_i': 0.0,
        # 'gfci_2_time': 0,
        # 'gfci_fault_value': 0.0,
        # 'grid_power_adjust': 0,
        # 'grid_r_voltage_adjust': 0,
        # 'grid_s_voltage_adjust': 0,
        # 'grid_t_voltage_adjust': 0,
        # 'i_ac1': 0.27,
        # 'i_battery': 6.47,
        # 'i_grid_port': 2.57,
        # 'i_pv1': 0.3,
        # 'i_pv2': 0.3,
        # 'inverter_countdown': 0,
        # 'inverter_status': 1,
        # 'island_check_continue': 0,
        # 'iso1': 0,
        # 'iso2': 0,
        # 'iso_fault_value': 0.0,
        "enable_local_command_test": False,
        # 'p_battery': 360,
        # 'p_eps_backup': 0,
        # 'p_grid_apparent': 554,
        # 'p_grid_out': 21,
        # 'p_inverter_out': 536,
        # 'p_load_demand': 515,
        # 'p_pv': 245,
        # 'p_pv1': 117,
        # 'p_pv2': 128,
        # 'pf_cmd_memory_state': True,
        # 'pf_inverter_out': -0.0469,
        # 'pf_limit_lp1_lp': 255,
        # 'pf_limit_lp1_pf': 1.0,
        # 'pf_limit_lp2_lp': 255,
        # 'pf_limit_lp2_pf': 1.0,
        # 'pf_limit_lp3_lp': 255,
        # 'pf_limit_lp3_pf': 1.0,
        # 'pf_limit_lp4_lp': 255,
        # 'pf_limit_lp4_pf': 1.0,
        "power_factor_function_model": PowerFactorFunctionModel.PF_1,
        # 'pv1_power_adjust': 0,
        # 'pv1_voltage_adjust': 0,
        # 'pv2_power_adjust': 0,
        # 'pv2_voltage_adjust': 0,
        "pv_power_setting": None,
        "v_pv_start": 150.0,
        # 'real_v_f_value': 0.0,
        # 'reboot': 0,
        # 'remote_bms_restart': False,
        "restart_delay_time": 30,
        # 'safety_time_limit': 0.0,
        # 'safety_v_f_limit': 0.0,
        "start_countdown_timer": 30,
        "start_system_auto_test": False,
        # 'system_mode': 1,
        # 'temp_battery': 16.0,
        # 'temp_charger': 24.1,
        # 'temp_fault_value': 0.0,
        # 'temp_inverter_heatsink': 24.4,
        # 'test_treat_time': 0,
        # 'test_treat_value': 0.0,
        # 'test_value': 0.0,
        "threephase_abc": 0,
        "threephase_balance_1": 0,
        "threephase_balance_2": 0,
        "threephase_balance_3": 0,
        "threephase_balance_mode": 0,
        # 'usb_device_inserted': 2,
        # 'user_code': 7,
        # 'v_10_min_protection': 274.0,
        # 'v_ac1': 236.3,
        # 'v_ac_fault_value': 0.0,
        # 'v_ac_high_c': 283.7,
        # 'v_ac_high_in': 262.0,
        # 'v_ac_high_in_time': 52,
        # 'v_ac_high_out': 274.0,
        # 'v_ac_high_out_time': 27,
        # 'v_ac_low_c': 175.5,
        # 'v_ac_low_in': 184.0,
        # 'v_ac_low_in_time': 126,
        # 'v_ac_low_out': 184.0,
        # 'v_ac_low_out_time': 126,
        # 'v_battery': 51.73,
        # 'v_eps_backup': 235.10,
        # 'v_highbrigh_bus': 2829,
        # 'v_n_bus': 0.0,
        # 'v_p_bus': 383.0,
        # 'v_pv1': 357.0,
        # 'v_pv2': 369.70,
        # 'v_pv_fault_value': 0.0,
        # 'work_time_total': 385,
        "active_power_rate": 100,
        "arm_firmware_version": 449,
        "battery_max_power": 2600,
        "battery_calibration_stage": BatteryCalibrationStage.OFF,
        "battery_capacity_ah": 160,

        "battery_capacity_kwh": 8.192,
        "battery_power_mode": BatteryPowerMode.SELF_CONSUMPTION,
        "battery_type": BatteryType.LITHIUM,
        "bms_firmware_version": 101,
        "charge_slot_2": TimeSlot(datetime.time(0, 0), datetime.time(0, 4)),
        "charge_soc": 0,
        "device_type_code": "2001",
        "discharge_slot_1": TimeSlot.from_repr(0, 0),
        "discharge_slot_2": TimeSlot.from_repr(0, 0),
        "discharge_soc": 0,
        "dsp_firmware_version": 449,
        "enable_60hz_freq_mode": False,
        "enable_ammeter": True,
        "enable_auto_judge_battery_type": True,
        "enable_charge_target": False,
        "enable_discharge": False,
        "enable_drm_rj45_port": True,
        "enable_inverter": True,
        "enable_inverter_auto_restart": False,
        "enable_reversed_115_meter": False,
        "enable_reversed_418_meter": False,
        "enable_reversed_ct_clamp": True,
        "firmware_version": "D0.449-A0.449",
        "first_battery_bms_firmware_version": 3005,
        "first_battery_serial_number": "BG1234G567",
        "grid_port_max_power_output": 6000,
        "meter_type": MeterType.EM115,
        "modbus_address": 0x11,
        "modbus_version": "1.40",
        "model": Model.HYBRID,
        "inverter_max_power": 5000,
        "module": "00030832",
        "num_mppt": 2,
        "num_phases": 1,
        "power_factor": 0,
        "reactive_power_rate": 0,
        "select_arm_chip": False,
        "serial_number": "SA1234G567",
        "status": Status.NORMAL,
        "v_pv1": 357.0,
        "v_pv2": 369.7,
        "v_p_bus": 383.0,
        "v_n_bus": 0.0,
        "v_ac1": 236.3,
        "e_battery_throughput": 356.5,
        "i_pv1": 0.3,
        "i_pv2": 0.3,
        "i_ac1": 2.7,
        "e_pv_total": 26.3,
        "f_ac1": 49.96,
        "charge_status": 5,
        "v_highbrigh_bus": 282.9,
        "pf_inverter_output_now": 9531,
        "e_pv1_day": 0.4,
        "p_pv1": 117,
        "e_pv2_day": 0.6,
        "p_pv2": 128,
        "e_grid_out_total": 0.9,
        "e_solar_diverter": 0.0,
        "p_grid_out_ph1": 536,
        "e_grid_out_day": 0.0,
        "e_grid_in_day": 19.8,
        "e_inverter_in_total": 188.1,
        "e_discharge_year": 0.0,
        "p_grid_out": 21,
        "p_backup": 0,
        "e_grid_in_total": 624.2,
        "e_load_day": 9.3,
        "e_battery_charge_day": 9.1,
        "e_battery_discharge_day": 3.4,
        "countdown": 0,
        "fault_code": "00000000",
        "t_inverter_heatsink": 24.4,
        "p_load_demand": 515,
        "p_grid_apparent": 554,
        "e_inverter_out_day": 3.8,
        "e_inverter_out_total": 172.5,
        "work_time_total": 385,
        "system_mode": 1,
        "v_battery": 51.73,
        "i_battery": 6.47,
        "p_battery": 360,
        "v_ac1_output": 235.1,
        "f_ac1_output": 49.92,
        "t_charger": 24.1,
        "t_battery": 16.0,
        "charger_warning_code": 0,
        "i_grid_port": 2.57,
        "battery_soc": 68,
        "system_time": datetime.datetime(2022, 1, 11, 11, 51, 46),
        "usb_device_inserted": UsbDevice.DISK,
        "user_code": 7,
        "variable_address": 32768,
        "variable_value": 30235,
        "battery_voltage_adjust": 0.0,
        "inverter_reboot": 0,
        "enable_rtc": False,
        "inverter_errors": None,
        "inverter_fault_messages": None,
        "charge_target_soc_1": None,
        "charge_slot_2_x": None,
        "charge_target_soc_2": None,
        "charge_slot_3": None,
        "charge_target_soc_3": None,
        "charge_slot_4": None,
        "charge_target_soc_4": None,
        "charge_slot_5": None,
        "charge_target_soc_5": None,
        "charge_slot_6": None,
        "charge_target_soc_6": None,
        "charge_slot_7": None,
        "charge_target_soc_7": None,
        "charge_slot_8": None,
        "charge_target_soc_8": None,
        "charge_slot_9": None,
        "charge_target_soc_9": None,
        "charge_slot_10": None,
        "charge_target_soc_10": None,
        "discharge_target_soc_1": None,
        "discharge_target_soc_2": None,
        "discharge_slot_3": None,
        "discharge_target_soc_3": None,
        "discharge_slot_4": None,
        "discharge_target_soc_4": None,
        "discharge_slot_5": None,
        "discharge_target_soc_5": None,
        "discharge_slot_6": None,
        "discharge_target_soc_6": None,
        "discharge_slot_7": None,
        "discharge_target_soc_7": None,
        "discharge_slot_8": None,
        "discharge_target_soc_8": None,
        "discharge_slot_9": None,
        "discharge_target_soc_9": None,
        "discharge_slot_10": None,
        "discharge_target_soc_10": None,
        "battery_charge_limit_ac": None,
        "battery_discharge_limit_ac": None,
        "battery_pause_mode": None,
        "battery_pause_slot_1": None,
        "e_battery_discharge_2": 173.0,
        "e_battery_charge_2": 183.5,
        "e_battery_discharge_day_2": 3.4,
        "e_battery_charge_day_2": 9.1,
        "p_combined_generation": None,
    }


def test_model_missing_guard():
    """Unknown single-char or non-string values raise ValueError rather than recursing."""
    import pytest

    with pytest.raises(ValueError):
        Model("9")  # single char, not a member
    with pytest.raises(ValueError):
        Model("9999")  # multi-char, first char also not a member


def test_model_coarse_lookup():
    """Model(dtc) returns the coarse family regardless of specific variant."""
    assert Model("2") is Model.HYBRID
    assert Model("2001") is Model.HYBRID
    assert Model("2101") is Model.HYBRID
    assert Model("4001") is Model.HYBRID_3PH
    assert Model("4101") is Model.HYBRID_3PH  # AIO_COMMERCIAL falls back to HYBRID_3PH family
    assert Model("5101") is Model.EMS  # EMS_COMMERCIAL falls back to EMS family
    assert Model("8101") is Model.ALL_IN_ONE  # HYBRID_HV_GEN3 falls back to ALL_IN_ONE family
    assert Model("8201") is Model.ALL_IN_ONE
    assert Model("8301") is Model.ALL_IN_ONE


def test_model_specific_variants():
    """Specific variants are reachable by direct construction."""
    assert Model("20g1") is Model.HYBRID_GEN1
    assert Model("20g2") is Model.HYBRID_GEN2
    assert Model("20g3") is Model.HYBRID_GEN3
    assert Model("21") is Model.POLAR
    assert Model("41") is Model.AIO_COMMERCIAL
    assert Model("51") is Model.EMS_COMMERCIAL
    assert Model("81") is Model.HYBRID_HV_GEN3
    assert Model("82") is Model.ALL_IN_ONE_HYBRID
    assert Model("83") is Model.HYBRID_GEN4


@pytest.mark.parametrize(
    "raw_dtc, arm_fw, expected",
    [
        # DTC "20xx" — generation depends on ARM firmware century
        (0x2001, 250, Model.HYBRID_GEN1),  # century 2 → GEN1
        (0x2001, 199, Model.HYBRID_GEN1),  # century 1 → GEN1
        (0x2001, 350, Model.HYBRID_GEN3),  # century 3 → GEN3
        (0x2001, 399, Model.HYBRID_GEN3),  # century 3 → GEN3
        (0x2001, 850, Model.HYBRID_GEN2),  # century 8 → GEN2
        (0x2001, 950, Model.HYBRID_GEN2),  # century 9 → GEN2
        (0x2003, 310, Model.HYBRID_GEN3),  # different power rating, same gen
        # Specific two-digit prefixes
        (0x2101, 100, Model.POLAR),
        (0x4001, 100, Model.HYBRID_3PH),
        (0x4101, 100, Model.AIO_COMMERCIAL),
        (0x5001, 100, Model.EMS),
        (0x5101, 100, Model.EMS_COMMERCIAL),
        (0x6001, 100, Model.AC_3PH),
        (0x7001, 100, Model.GATEWAY),
        (0x8001, 100, Model.ALL_IN_ONE),
        (0x8101, 100, Model.HYBRID_HV_GEN3),
        (0x8201, 100, Model.ALL_IN_ONE_HYBRID),
        (0x8301, 100, Model.HYBRID_GEN4),
    ],
)
def test_resolve_model(raw_dtc, arm_fw, expected):
    assert resolve_model(raw_dtc, arm_fw) is expected


@pytest.mark.parametrize(
    "model,expected",
    [
        (Model.ALL_IN_ONE, 307.0),
        (Model.HYBRID_3PH, 76.8),
        (Model.AC_3PH, 76.8),
        (Model.HYBRID, 51.2),
    ],
)
def test_model_system_battery_voltage(model, expected):
    assert model.system_battery_voltage == expected


def test_single_phase_inverter_slot_map():
    from givenergy_modbus.model.inverter import EXTENDED_SLOTS, SINGLE_PHASE_SLOTS
    from givenergy_modbus.model.register import HR

    # Default (no DTC set) → legacy 2-slot map
    assert SinglePhaseInverter.from_register_cache(RegisterCache()).slot_map is SINGLE_PHASE_SLOTS

    # HYBRID_GEN1 / GEN2 → legacy
    for dtc_hex in (0x2001, 0x2002):
        cache = RegisterCache({HR(0): dtc_hex, HR(21): 100})
        assert SinglePhaseInverter.from_register_cache(cache).slot_map is SINGLE_PHASE_SLOTS

    # HYBRID_GEN3 with fw ≤ 302 → legacy
    cache = RegisterCache({HR(0): 0x2003, HR(21): 302})
    assert SinglePhaseInverter.from_register_cache(cache).slot_map is SINGLE_PHASE_SLOTS

    # HYBRID_GEN3 with fw > 302 → extended
    cache = RegisterCache({HR(0): 0x2003, HR(21): 303})
    assert SinglePhaseInverter.from_register_cache(cache).slot_map is EXTENDED_SLOTS

    # ALL_IN_ONE (80xx), HYBRID_GEN4 (83xx), HYBRID_HV_GEN3 (81xx) → extended
    for dtc_hex in (0x8001, 0x8301, 0x8101):
        cache = RegisterCache({HR(0): dtc_hex, HR(21): 100})
        assert SinglePhaseInverter.from_register_cache(cache).slot_map is EXTENDED_SLOTS


def test_single_phase_inverter_p_pv_and_e_pv_day():
    from givenergy_modbus.model.register import IR

    cache = RegisterCache({IR(18): 1000, IR(20): 500, IR(17): 12, IR(19): 8})
    inv = SinglePhaseInverter.from_register_cache(cache)
    assert inv.p_pv() == 1500  # type: ignore[attr-defined]
    assert inv.e_pv_day() == 2.0  # type: ignore[attr-defined]


def test_inverter_max_power():
    from givenergy_modbus.model.inverter import _DTC_RATED_POWER
    from givenergy_modbus.model.register import HR

    # Known DTC → correct wattage via computed field
    cache = RegisterCache({HR(0): 0x2001})
    assert SinglePhaseInverter.from_register_cache(cache).inverter_max_power == 5000  # type: ignore[attr-defined]
    # DTC not in rated-power LUT → None
    cache = RegisterCache({HR(0): 0x2009})
    assert SinglePhaseInverter.from_register_cache(cache).inverter_max_power is None  # type: ignore[attr-defined]
    # No DTC at all → None
    cache = RegisterCache()
    assert SinglePhaseInverter.from_register_cache(cache).inverter_max_power is None  # type: ignore[attr-defined]
    # LUT covers 3-phase and AIO variants
    assert _DTC_RATED_POWER.get("4003") == 10000
    assert _DTC_RATED_POWER.get("8204") == 12000


def test_inverter_deprecation_alias():
    import givenergy_modbus.model.inverter as inv_module

    with warnings.catch_warnings(record=True) as w:
        warnings.simplefilter("always")
        cls = inv_module.Inverter  # type: ignore[attr-defined]
    assert cls is SinglePhaseInverter
    assert len(w) == 1
    assert issubclass(w[0].category, DeprecationWarning)
    assert "SinglePhaseInverter" in str(w[0].message)


def test_inverter_getattr_unknown():
    import givenergy_modbus.model.inverter as inv_module

    with pytest.raises(AttributeError, match="has no attribute"):
        _ = inv_module.NonExistentAttribute  # type: ignore[attr-defined]
